version: "3.9"
services:

  web:
    restart: always
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/code
    environment:
      - DEBUG=False
      - SECRET_KEY=${SECRET_KEY}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_OPTIONS=${DB_OPTIONS}


